language: nix
nix: 2.1.3
cache:
  directories:
    - $HOME/nix.store
before_install:
  - sudo mkdir -p /etc/nix
  - echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
  - echo "substituters = file://$HOME/nix.store https://cache.nixos.org/" | sudo tee -a /etc/nix/nix.conf
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf
script:
  - nix build --arg pkgs 'import <nixpkgs> {config = {}; }' -f default.nix --show-trace
before_cache:
  - rm -rf $HOME/nix.store
  - mkdir -p $HOME/nix.store
  - nix copy --arg pkgs 'import <nixpkgs> {config = {}; }' --to file://$HOME/nix.store -f Cargo.nix 'root_crate.buildInputs' || echo "skipped buildInputs"
  - nix copy --arg pkgs 'import <nixpkgs> {config = {}; }' --to file://$HOME/nix.store -f default.nix || echo "skipped default.nix"