[package]
name = "multiple_bin"
version = "0.1.0"
authors = ["Kristoffer Søholm <k.soeholm@gmail.com>"]
edition = "2018"

[[bin]]
name = "bin1"
path = "src/bin1.rs"

[[bin]]
name = "bin2"
path = "src/bin2.rs"

[dependencies]

