name: "tests-nix-macos"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform:
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@releases/v7
    - uses: cachix/cachix-action@releases/v6
      with:
        name: eigenvalue
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: "./run_tests.sh --no-cargo-build"
