name: "tests-nix"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform: 
          - ubuntu-latest 
          # macos-latest had problems in the past.
          # https://github.com/cachix/cachix-action/issues/27
          # - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v3
      with:
        name: eigenvalue
        file: 'tests.nix'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
