name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - uses: cachix/cachix-action@v2
      with:
        name: eigenvalue
        file: 'tests.nix'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'